config/routes.rb
Rails.application.routes.draw do

  get 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  resources :users
  resources :registration

  root to: 'users#home'

  get 'static_pages/home', to: 'static_pages#home'

  resources :gossips do
  resources :comments
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :gossip, optional: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.create(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
  end
  
  def update
     @gossip = Gossip.find(params[:gossip_id])
     @comment = @gossip.comments.find(params[:id])
     @comment.update(comment_params)
     redirect_to gossip_path(@gossip.id)
  end

  def destroy
     @gossip = Gossip.find(params[:gossip_id])
     @comment = @gossip.comments.find(params[:id])
     @comment.destroy
     redirect_to gossip_path(@gossip.id)
  end


  private

  def comment_params
    params.require(:comment).permit(:anonymous_commentor, :content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossip = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

def new
end




end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    @current_user = User.find_by_id(session[:current_user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user.id)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to gossip_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def home
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def login

  end

  def check
    @user = User.where(email:params[:email], password:params[:password]).first
    puts @user
    if @user
      flash[:info] = "Vous êtes bien connecté #{@user.first_name} !"
      redirect_to "/users/home"
    else
      flash[:info] = "Échec "
      redirect_to "/users/login"
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :email, :last_name, :age, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>&Eacute;diter le commentaire n°<%= @comment.id %></h1>

h2> Ajouter un commentaire </h2>

<%= form_for([@gossip, @comment]) do |f| %>
  <p>
    <%= f.label :anonymous_commentor, "Ton petit nom" %><br>
    <%= f.text_field :anonymous_commentor %>
  </p>
  <p>
    <%= f.label :content, "Ton commentaire" %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Publier mon commentaire" %>
  </p>
<% end %>

<%= link_to 'Clique pour détruire',[@comment.gossip, @comment], method: :delete%>

app/views/gossips/create.html.erb
<h1>Gossip#create</h1>
<p>Find me in app/views/gossip/create.html.erb</p>

app/views/gossips/edit.html.erb
<h1>&Eacute;diter le gossip n°<%= @gossip.id %></h1>

<%= form_for @gossip do |f| %>
<label>Le titre : </label><%= @gossip.title %>
<%= f.label :content, "Le contenu" %>
<%= f.text_area :content %>
<%= f.label :anonymous_gossiper, "Ton petit nom" %>
<%= f.text_field :anonymous_gossiper %>
<%= f.submit "Modifier le gossip" %>
<% end %>

<%= link_to 'Clique pour détruire', @gossip, method: :delete %>

app/views/gossips/index.html.erb
<table>
  <tbody>
    <thead>
      <tr>
        <td>Numéro du gossip</td>
        <td>Titre du gossip</td>
        <td>Contenu du gossip</td>
        <td>Auteur du contenu</td>
        <td>Lien du gossip</td>
        `<td>Nombre de commentaires</td>
      </tr>
    </thead>
  <% Gossip.all.each do |gossip| %>
    <tr>
      <td><%= gossip.id %></td>
      <td><%= gossip.title %></td>
      <td><%= gossip.content %></td>
      <td><%= gossip.anonymous_gossiper %></td>
      <td><%= link_to 'Voir le gossip', gossip_path(gossip.id) %><td>
      <td><%= gossip.comments.count %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Enregistre toi', new_user_path,  class:"btn btn-primary"%>
<%= link_to 'Créer un nouveau gossip', new_gossip_path,  class:"btn btn-primary"%>

app/views/gossips/new.html.erb
<h1>Créer un gossip</h1>

<%= form_for @gossip do |f| %>
<%= f.label :title, "Le titre"%>
<%= f.text_field :title%>
<%= f.label :content, "Le contenu"%>
<%= f.text_area :content %>
<%= f.label :anonymous_gossiper, "Ton petit nom"%>
<%= f.text_field :anonymous_gossiper %>
<%= f.submit "Créer le gossip" %>
<% end %>

app/views/gossips/show.html.erb
<h1> Voici le gossip n°<%= @gossip.id %></h1>

<p> <%= @gossip.title %> </p>
<p> Son contenu : <%= @gossip.content %> </p>
<p> Son auteur : <%= @gossip.anonymous_gossiper %> </p>
<p><%= link_to "Editer le gossip", edit_gossip_path(@gossip) %> </p>
<p><%= link_to "Retour à l'accueil", static_pages_home_path %> </p>

<!-- COMMENTAIRES -->

<h2>Commentaires</h2>
  <% @gossip.comments.each do |comment| %>
    <p>
      <strong>Anonymous Commentor :</strong>
      <%= comment.anonymous_commentor %>
    </p>

    <p>
      <strong>Commentaire :</strong>
      <%= comment.content %>
    </p>

<p><%= link_to "Editer le commentaire", edit_gossip_comment_path(@gossip, comment) %></p>

  <% end %>

<!-- AJOUTER UN COMMENTAIRE -->

<h2> Ajouter un commentaire </h2>
<%= form_for([@gossip, Comment.new]) do |f| %>
  <p>
    <%= f.label :anonymous_commentor, "Ton petit nom" %><br>
    <%= f.text_field :anonymous_commentor %>
  </p>
  <p>
    <%= f.label :content, "Ton commentaire" %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Publier mon commentaire" %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", '/' %></li>
        <li><%= link_to "Index des gossips", gossips_path %></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= render "layouts/header" %>
  </head>

  <body>
  <div><%= flash[:info] %></div>
  <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Enregistrer n°<%= @user.id %></h1>

<%= form_for @user do |f| %>

<%= f.label :first_name, "Ton prenom"%></br>
<%= f.text_field :first_name%></br>

<%= f.label :last_name, "ton nom"%></br>
<%= f.text_field :last_name%></br>

<%= f.label :email, "Ton mail"%></br>
<%= f.email_field :email %></br>

<%= f.label :age, "Ton age"%></br>
<%= f.number_field :age %></br>

<%= f.label :password, "mot de passe "%></br>
<%= f.text_field :password %></br>

<%= f.submit "Modifier " %>
<% end %>

<%= link_to 'Clique pour détruire', @user, method: :delete, class:"btn btn-primary"%>

app/views/users/home.html.erb
<a href="/users/login">S'identifier</a>
  <% if @user %>
    <h1>Bienvenue <%= @user.first_name %> !</h1>
  <% else %>
    <h1>Tu vas pouvoir creer un gossip !</h1>
    <a href="/users/login">S'identifier</a>
  <% end %>

app/views/users/login.html.erb
<h1>Connexion</h1>
<a href="/users/home">Retourner à l'accueil</a>
<%= form_tag "/users/login", method: :post do %>
  <input type="text" name="email" />
  <input type="password" name="password" />
  <input type="submit" value="Se connecter" />
<% end %>

app/views/users/new.html.erb
<h1>utilisateur</h1>

<%= form_for @user do |f| %></br>
<%= f.label :first_name, "Ton prenom"%></br>
<%= f.text_field :first_name%></br>

<%= f.label :last_name, "ton nom"%></br>
<%= f.text_field :last_name%></br>

<%= f.label :email, "Ton mail"%></br>
<%= f.email_field :email %></br>

<%= f.label :age, "Ton age"%></br>
<%= f.number_field :age %></br>

<%= f.label :password, "mot de passe "%></br>
<%= f.text_field :password %></br>

<%= f.submit "Enregistre toi" , class:"btn btn-primary"%></br>
<% end %>

app/views/users/show.html.erb
<h1> Bienvenue dans gossip <%= @user.first_name%></h1>


<p><%= link_to "Edite ton profil", edit_user_path(@user), class:"btn btn-primary"%> </p>
<p><%= link_to "Retour à l'accueil", static_pages_home_path, class:"btn btn-primary" %> </p>